name: xoak
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - xarray
  - dask
  - scipy
  - scikit-learn
  - pys2index
  - pytest
  - pytest-cov
  - pydata-sphinx-theme=0.15.4
  - sphinx-book-theme=1.1.4
